/*Enemy*/
global.enemy_name = [];
global.enemy_speed = [];
global.enemy_hp = [];
global.enemy_type_bullet = [];
global.enemy_type_bullet_boss = [];
global.enemy_sprite = [];
global.enemy_limit_y = [];
global.enemy_destroy = [];
global.enemy_dmg_collision = [];
global.enemy_not_destroy = [];
global.enemy_follow_player = [];
//ID: 0
global.enemy_name[0] = "Light ship";
global.enemy_speed[0] = 4;
global.enemy_hp[0] = 60;
global.enemy_type_bullet[0] = 0;
global.enemy_type_bullet_boss[0] = -1;
global.enemy_sprite[0] = spr_enemy_1
global.enemy_limit_y[0] = -1;
global.enemy_destroy[0] = -2;
global.enemy_dmg_collision [0] = 15
global.enemy_not_destroy[0] = false;
global.enemy_follow_player[0] = false;
//ID: 1
global.enemy_name[1] = "Boss 1";
global.enemy_speed[1] = 3;
global.enemy_hp[1] = 3000;
global.enemy_type_bullet[1] = 2;
global.enemy_type_bullet_boss[1] = 3;
global.enemy_sprite[1] = spr_boss_1
global.enemy_limit_y[1] = 200
global.enemy_destroy[1] = 1
global.enemy_dmg_collision[1] = 99999
global.enemy_not_destroy[1] = false;
global.enemy_follow_player[1] = false;
//ID: 02
global.enemy_name[2] = "Heavy ship";
global.enemy_speed[2] = 2;
global.enemy_hp[2] = 140;
global.enemy_type_bullet[2] = 1;
global.enemy_type_bullet_boss[2] = -1;
global.enemy_sprite[2] = spr_enemy_2
global.enemy_limit_y[2] = -1;
global.enemy_destroy[2] = -2;
global.enemy_dmg_collision [2] = 25
global.enemy_not_destroy[2] = false;
global.enemy_follow_player[2] = false;
//ID: 03
global.enemy_name[3] = "Fire Storm";
global.enemy_speed[3] = 1.35;
global.enemy_hp[3] = -9999;
global.enemy_type_bullet[3] = 1;
global.enemy_type_bullet_boss[3] = -1;
global.enemy_sprite[3] = spr_enemy_4
global.enemy_limit_y[3] = -1;
global.enemy_destroy[3] = -2;
global.enemy_dmg_collision [3] = 25
global.enemy_not_destroy[3] = true;
global.enemy_follow_player[3] = false;
//ID: 04
global.enemy_name[4] = "Bommer";
global.enemy_speed[4] = 15;
global.enemy_hp[4] = 300;
global.enemy_type_bullet[4] = -1;
global.enemy_type_bullet_boss[4] = -1;
global.enemy_sprite[4] = spr_enemy_5
global.enemy_limit_y[4] = -1;
global.enemy_destroy[4] = -2;
global.enemy_dmg_collision [4] = 100
global.enemy_not_destroy[4] = false;
global.enemy_follow_player[4] = true;
